[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.13",
    "fastapi[standard]>=0.116.1",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]
