name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Run Ruff Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv (+ Python 3.12)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Ruff check
        run: uvx ruff check --output-format=github .

  deploy:
    name: Deploy (Docker Compose on self-hosted)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ci]
    runs-on: self-hosted
    environment: production
    steps:
      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
